### ISSUE TITLE
Failed to activate the tidal-autocode package

### ISSUE THREAD

**Issue by freekatet** [kindohm/tidal-autocode#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.4 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.5
**Thrown From**: [tidal-autocode](https://github.com/kindohm/tidal-autocode) package 0.6.4

### Stack Trace

Failed to activate the tidal-autocode package

```
At Cannot find module 'tracery-grammar'

Error: Cannot find module 'tracery-grammar'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/tidal-autocode/lib/raver.js:5:15)
    at /packages/tidal-autocode/lib/raver.js:15:2)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/tidal-autocode/lib/tidal-autocode.js:7:14)
    at /packages/tidal-autocode/lib/tidal-autocode.js:90:2)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:887:35)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:242:22)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:968:31
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:246:26)
```

### Commands

```
     -0:10.3.0 tidal-autocode:start (atom-pane.pane)
```

### Non-Core Packages

```
tidal-autocode 0.6.4 
tidalcycles 0.9.2 
```

**Comment by b1tdreamer** [comment]
Same error here. Any ideas?

**Comment by kindohm** [comment]
Sorry for the delay. I'll take a look soon. I'm wondering if the tracery package just got renamed.

**Comment by kindohm** [comment]
I cannot reproduce this. I'm running:

Windows 10 
Tidal 0.9.6
Atom 1.25.0 

I removed Atom and deleted all `.atom` and package folders to ensure that I don't have any cached data. After a fresh Atom install I cannot reproduce the issue, and the `tracery-grammar` module gets loaded. 

@b1tdreamer, can you provide more info on your system and Atom environment? @freekatet, are you still experiencing the problem?

**Comment by b1tdreamer** [comment]
Hi Kindohm and thanks for your reply, my environment:

Windows 10
Tidal 0.9.9 (just updated)
Atom 1.25.0

It's very strage, after tidalcycles update I launched tidal-autocode and it worked for a while. I closed Atom, opened it again and I return to the same error "At Cannot find module 'tracery-grammar'".

No idea at all what's happening...

**Comment by Xon77** [comment]
Hello, I try to make your package work, even if the code dates back to several years. Trying... Maybe, you know what the problem is, even if you are not working on it anymore. When I try to start it from the packages menu, I've got the following message.

I am on MacOS 15.4 with Pulsar with Tidal 1.9.5 

> Failed to activate the tidal-autocode package
Cannot find module 'tracery-grammar'
Require stack:
- /Users/xon/.pulsar/packages/tidal-autocode/lib/raver.js
- /Users/xon/.pulsar/packages/tidal-autocode/lib/tidal-autocode.js
- /Applications/Pulsar.app/Contents/Resources/app.asar/src/module-utils.js
- /Applications/Pulsar.app/Contents/Resources/app.asar/src/package.js
- /Applications/Pulsar.app/Contents/Resources/app.asar/src/package-manager.js
- /Applications/Pulsar.app/Contents/Resources/app.asar/src/atom-environment.js
- /Applications/Pulsar.app/Contents/Resources/app.asar/src/initialize-application-window.js
- /Applications/Pulsar.app/Contents/Resources/app.asar/static/index.html
[Hide Stack Trace](https://github.com/kindohm/tidal-autocode/issues/1#)
Error: Cannot find module 'tracery-grammar'
Require stack:
- /Users/xon/.pulsar/packages/tidal-autocode/lib/raver.js
- /Users/xon/.pulsar/packages/tidal-autocode/lib/tidal-autocode.js
- /Applications/Pulsar.app/Contents/Resources/app.asar/src/module-utils.js
- /Applications/Pulsar.app/Contents/Resources/app.asar/src/package.js
- /Applications/Pulsar.app/Contents/Resources/app.asar/src/package-manager.js
- /Applications/Pulsar.app/Contents/Resources/app.asar/src/atom-environment.js
- /Applications/Pulsar.app/Contents/Resources/app.asar/src/initialize-application-window.js
- /Applications/Pulsar.app/Contents/Resources/app.asar/static/index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at o._resolveFilename (electron/js2c/renderer_init.js:33:1118)
    at Function.Module._resolveFilename (/Applications/Pulsar.app/Contents/Resources/app.asar/src/module-cache.js:317:28)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.o._load (electron/js2c/renderer_init.js:33:379)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (/Applications/Pulsar.app/Contents/Resources/app.asar/src/native-compile-cache.js:67:27)
    at Object.<anonymous> (raver.js:5:15)
    at Object.<anonymous> (raver.js:15:2)
    at Module._compile (/Applications/Pulsar.app/Contents/Resources/app.asar/src/native-compile-cache.js:120:30)
    at Object.value [as .js] (/Applications/Pulsar.app/Contents/Resources/app.asar/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.o._load (electron/js2c/renderer_init.js:33:379)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (/Applications/Pulsar.app/Contents/Resources/app.asar/src/native-compile-cache.js:67:27)
    at Object.<anonymous> (tidal-autocode.js:3:1)
    at Object.<anonymous> (tidal-autocode.js:90:2)
    at Module._compile (/Applications/Pulsar.app/Contents/Resources/app.asar/src/native-compile-cache.js:120:30)
    at Object.value [as .js] (/Applications/Pulsar.app/Contents/Resources/app.asar/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.o._load (electron/js2c/renderer_init.js:33:379)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (/Applications/Pulsar.app/Contents/Resources/app.asar/src/native-compile-cache.js:67:27)
    at requireModule (/Applications/Pulsar.app/Contents/Resources/app.asar/src/module-utils.js:3:17)
    at Package.requireMainModule (/Applications/Pulsar.app/Contents/Resources/app.asar/src/package.js:916:27)
